version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: lp
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./lp:/usr/share/nginx/html